# **Lesson 1. 연산자와 기본 자료형_종합실습**

**1) 세 개의 변수에 이름, 키, 몸무게를 각각 대입하고 하나의 print() 함수로 출력하세요.**

- 단, 변수 이름은 가지고 있는 값의 의미를 알 수 있게 적절히 선언하세요

[결과 예시] 이름: 홍길동, 키: 175, 몸무게: 70을 각각 대입한 경우

~~~
홍길동 175 70
~~~

In [ ]:
# 변수 선언
name = '홍길동'
tall = 175
weight = 70

# 확인
print(name, tall, weight)

**2) 다음 구문의 결과를 확인한 후 이어지는 코드 셀에 복합 대입 연산자를 사용해 다시 작성하세요.**

[결과 예시]

~~~
40.0
~~~

In [ ]:
# 변수 선언
num1 = 50

# 사칙연산(기본연산자)
num1 = num1 + 10
num1 = num1 / 2
num1 = num1 - 10
num1 = num1 * 2

# 확인
print(num1)

In [ ]:
# 변수 선언
num1 = 50

# 사칙연산(복합 대입 연산자)
num1 += 10
num1 /= 2
num1 -= 10
num1 *= 2

# 확인
print(num1)

**3) 다음 변수들의 합계와 평균을 tot_score, avg_score 변수에 대입한 후 출력하세요.**

[결과 예시]

~~~
합계: 1104 평균: 220.8
~~~

In [ ]:
# 변수 선언
score1 = 153
score2 = 204
score3 = 259
score4 = 221
score5 = 267

# 합계 구하기
tot_score = score1 + score2 + score3 + score4 + score5

# 평균 구하기
avg_score = tot_score / 5

# 출력
print('합계:', tot_score, '평균:', avg_score)

**4) 홍길동의 과목별 점수는 아래와 같습니다.**

- 국어: 96, 수학: 72, 영어: 88, 역사: 80
- 변수 kor, math, eng, hist에 각 과목 점수를 대입한 뒤,
- 변수 avg에 평균 점수를 저장하여
- 문자열 '홍길동의 평균 점수는'과 avg를 하나의 print() 함수로 출력하세요.
- 힌트: 평균 = (요소 합) / (요소 개수)

[결과 예시]

~~~
홍길동의 평균 점수는 84.0
~~~

In [ ]:
# 변수 선언
kor = 96
math = 72
eng = 88
hist = 80

# 평균 구하기
avg = (kor + math + eng + hist) / 4

# 확인
print('홍길동의 평균 점수는', avg)

**5) 변수 name 또는 score에 적절한 형 변환을 수행해 다음 구문의 오류를 해결하세요**

- 힌트: 정수, 실수, 문자열 등으로 형 변환을 하는 함수들이 있습니다.

[결과 예시]

~~~
홍길동 점수는 950입니다.
~~~

In [ ]:
# 변수 선언
name = '홍길동'
score = 950

# 확인
print(name + ' 점수는 ' + score + '입니다.')

# TypeError: can only concatenate str (not "int") to str

In [ ]:
# 변수 선언
name = '홍길동'
score = 950

# 확인
print(name + ' 점수는 ' + str(score) + '입니다.')