# **Lesson 3. 리스트 자료형_종합실습**

**1) 다음 정수들을 요소로 갖는 리스트 score를 선언하고 확인하세요.**

- 85, 75, 85, 95, 95, 70, 65, 95, 90

[결과 예시]

~~~
[85, 75, 85, 95, 95, 70, 65, 95, 90]
~~~

In [ ]:
# 리스트 선언


# 확인

**2) 위에서 만든 리스트 score에 80을 요소로 추가하고 확인하세요.**

- 힌트: 요소를 하나 추가할 때 사용하는 메서드, 또는 연산자가 있습니다.

[결과 예시]

~~~
[85, 75, 85, 95, 95, 70, 65, 95, 90, 80]
~~~

In [ ]:
# 요소 추가


# 확인

**3) 리스트 score의 요소를 내림차순으로 정렬하고 확인하세요.**

- 힌트: 요소를 정렬할 때 사용하는 메서드가 있습니다.

[결과 예시]

~~~
[95, 95, 95, 90, 85, 85, 80, 75, 70, 65]
~~~

In [ ]:
# 정렬하기


# 확인

**4) 리스트 score의 합과 평균을 각각 score_sum, score_avg 변수로 선언하고 확인하세요.**

[결과 예시]

~~~
합계: 835
평균: 83.5
~~~

In [ ]:
# 합, 평균



# 확인

**5) 다음 도시 이름을 요소로 갖는 리스트 city를 선언하고 확인하세요.**

- 서울, 부산, 대구, 인천, 광주, 대전, 울산

[결과 예시]

~~~
['서울', '부산', '대구', '인천', '광주', '대전', '울산']
~~~

In [ ]:
# 리스트 선언


# 확인

**6) 리스트 city의 요소를 오름차순으로 정렬하고 확인하세요.**

- 힌트: 요소를 정렬할 때 사용하는 메서드가 있습니다.

[결과 예시]

~~~
['광주', '대구', '대전', '부산', '서울', '울산', '인천']
~~~

In [ ]:
# 정렬


# 확인

**7) 다음 요구에 따라 리스트 city에 대한 인덱싱과 슬라이싱을 수행하세요**

- 다섯 번째 도시 확인
- 대전 ~ 서울 확인
- 맨 앞 세 개 도시 확인
- 맨 뒤 두 개 도시 확인

[결과 예시]

~~~
서울
['대전', '부산', '서울']
['광주', '대구', '대전']
['울산', '인천']
~~~

In [ ]:
# 인덱싱, 슬라이싱

**8) 리스트 city에 다음 세 개의 도시를 추가하고, 다시 오름차순으로 정렬하고 확인하세요.**

- 수원, 용인, 고양
- 힌트: 여러 요소를 추가할 때 사용하는 메서드, 또는 연산자가 있습니다.

[결과 예시]

~~~
['고양', '광주', '대구', '대전', '부산', '서울', '수원', '용인', '울산', '인천']
~~~

In [ ]:
# 도시 추가, 정렬



# 확인