# **Topic 1. 리스트에 대한 이해_실습**

**1) 1, 2, 3, 4, 5를 요소로 갖는 리스트 a를 선언하고 확인하세요.**

[결과 예시]

~~~
[1, 2, 3, 4, 5]
~~~

In [ ]:
a = [1, 2, 3, 4, 5]
print(a)

**2) 1, '홍길동', 2, '일지매'를 요소로 갖는 리스트 c를 선언하고 확인하세요.**

[결과 예시]

~~~
[1, '홍길동', 2, '일지매']
~~~

In [ ]:
c = [1, '홍길동', 2, '일지매']
print(c)

**3) 1, 2, 3, 4를 요소로 갖는 리스트 a와, 5, 6, 7, 8을 요소로 갖는 리스트 b를 선언하고 확인하세요.**

[결과 예시]

~~~
[1, 2, 3, 4]
[5, 6, 7, 8]
~~~

In [ ]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
print(a)
print(b)

**4) 위 3)에서 선언한 리스트 a, b를 요소로 갖는 리스트 c를 선언하고 확인하세요.**

[결과 예시]

~~~
[[1, 2, 3, 4], [5, 6, 7, 8]]
~~~

In [ ]:
c = [a, b]
print(c)

**5) 위 3)에서 선언한 리스트 a와 b의 요소를 결합한 리스트 c를 선언하고 확인하세요.**

[결과 예시]

~~~
[1, 2, 3, 4, 5, 6, 7, 8]
~~~

In [ ]:
c = a + b
print(c)

**6) 1, 2, 3를 세 번 반복한 결과를 요소로 갖는 리스트 d를 선언하고 확인하세요.**

[결과 예시]

~~~
[1, 2, 3, 1, 2, 3, 1, 2, 3]
~~~

In [ ]:
d = [1, 2, 3] * 3
print(d)

**7) 다음 리스트의 요소들에 대한 최댓값, 최솟값, 합계, 평균을 확인하세요.**

[결과 예시]

~~~
최댓값: 95
최솟값: 60
합계: 780
평균: 78.0
~~~

In [ ]:
score = [80, 75, 70, 95, 90, 65, 85, 70, 90, 60]

In [ ]:
print('최댓값:', max(score))
print('최솟값:', min(score))
print('합계:', sum(score))
print('평균:', sum(score)/len(score))